=== mzanella/TecWebProject/data/database/DBfilm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti" targetNamespace="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti" elementFormDefault="qualified">
<xs:element name="database" type="Tdatabase" />

<xs:complexType name="Tdatabase">
	<xs:sequence>
		<xs:element name="films" type="Tfilms"  minOccurs="1" maxOccurs="1"/>
		<xs:element name="filmsProssimamente" type="TfilmsProssimamente"  minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="Tfilms">
	<xs:sequence>
		<xs:element name="film" type="Tfilm" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="TfilmsProssimamente">
	<xs:sequence>
		<xs:element name="filmProssimamente" type="TfilmProssimamente" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>



	<xs:complexType name="Tfilm">
		<xs:sequence>
			<xs:group ref="filmDatiComuni"/>
			<xs:element name="incasso" type="Tincasso" />
			<xs:element name="valutazioneSito" type="xs:positiveInteger" />
			<xs:element name="recensione" type="xs:string" />
			<xs:element name="inSala" type="Tsala" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="TfilmProssimamente">
		<xs:sequence>
			<xs:group ref="filmDatiComuni"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:decimal" />
	</xs:complexType>

	<xs:group name="filmDatiComuni">
		<xs:sequence>
				<xs:element name="locandina" type="Tlocandina" />
				<xs:element name="titolo" type="xs:string" />
				<xs:element name="dataUscita" type="xs:string" />
				<xs:element name="paese" type="xs:string" />
				<xs:element name="durata" type="xs:positiveInteger" />
				<xs:element name="trama" type="xs:string" />
				<xs:element name="genere" type="Tgenere" />
				<xs:element name="annoProduzione" type="xs:string" />
				<xs:element name="attori" type="xs:string" />
				<xs:element name="regia" type="xs:string" />
		</xs:sequence>
	</xs:group>

	<xs:complexType name="Tincasso">
	<xs:simpleContent>
		<xs:extension base="xs:positiveInteger">
			<xs:attribute name="valuta" use="required" fixed="&#8364;" type="xs:string"/>
			<xs:attribute name="unitaMisura" use="required" fixed="M." type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
	</xs:complexType>

<xs:simpleType name="Tsala">
		<xs:restriction base="xs:string">
			<xs:enumeration value="si" />
			<xs:enumeration value="no" />
		</xs:restriction>
</xs:simpleType>


<xs:complexType name="Tlocandina">
		<xs:attribute name="alt" type="xs:string" use="required"/>
		<xs:attribute name="src" type="xs:string" use="optional"/>
</xs:complexType>

<xs:simpleType name="Tgenere">
<xs:restriction base="xs:string">
	<xs:enumeration value="animazione" />
	<xs:enumeration value="avventura" />
	<xs:enumeration value="azione" />
	<xs:enumeration value="comico" />
	<xs:enumeration value="commedia" />
	<xs:enumeration value="documentario" />
	<xs:enumeration value="dramma" />
	<xs:enumeration value="erotico" />
	<xs:enumeration value="fantascienza" />
	<xs:enumeration value="giallo" />
	<xs:enumeration value="guerra" />
	<xs:enumeration value="horror" />
	<xs:enumeration value="musical" />
	<xs:enumeration value="noir" />
	<xs:enumeration value="sentimentale" />
	<xs:enumeration value="thriller" />
	<xs:enumeration value="western" />
</xs:restriction>
</xs:simpleType>

</xs:schema>

=== mzanella/TecWebProject/data/database/DBfilms.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti ../data/database/DBfilm.xsd">
<films>

<film id="0">
<locandina src="http://images.movieplayer.it/t/images/2015/11/20/hateful_eight_payoff_final_jpg_1003x0_crop_q85.jpg" alt="degli uomini camminano sotto la neve"/>
<titolo>The Hateful Eight</titolo>
<dataUscita>2016-02-02</dataUscita>
<paese>USA</paese>
<durata>187</durata>
<trama>Lungo i sentieri rocciosi del Wyoming, una diligenza corre più forte del vento. Un vento che promette furia e tempesta. Ultima corsa per Red Rock, la diligenza si arresta davanti al Maggiore Marquis Warren, diligence stopper e cacciatore di taglie nero che ha servito la causa dell&amp;#39;Unione. Ospitato con riserva da John Ruth, bounty hunter che crede nella giustizia, meno negli uomini, Warren lo rassicura sulle sue buone intenzioni. Il viaggio riprende ma il caratteraccio di Daisy Domergue, canaglia in gonnella condotta alla forca, lo interrompe di nuovo. La sosta imprevista incontra e carica tra chiacchiere e scetticismo Chris Mannix, un sudista rinnegato promosso sceriffo di Red Rock. Incalzati dal blizzard, trovano rifugio nell&amp;#39;emporio di Minnie dove li attendono un caffè caldo e quattro sconosciuti. Interrogati a turno dal diffidente John Ruth probabilmente nessuno è chi dice di essere.</trama>
<incasso valuta="euro" unitaMisura="M.">5</incasso>
<valutazioneSito>4</valutazioneSito>
<recensione>Nel teatro della Storia, la gente entra nelle vite altrui cambiandone la rotta. In The Hateful Eight sono otto le persone le cui vite si incrociano, un po’ per fato e un po’ per causa di forza maggiore. Siamo in Wyoming, poco dopo la Guerra di Secessione. Una bufera di neve colpisce una diligenza che sta portando John &amp;#39;The Hangman&amp;#39; Ruth (Russell) verso Red Rock, dove la donna che tiene prigioniera, l&amp;#39;assassina Daisy Domergue (Leigh), verrà condannata a morte e lui riceverà i diecimila dollari di taglia.&#13;
&#13;
I due incrociano prima il Maggiore Marquis Warren (Jackson) e poi il nuovo sceriffo di Red Rock, Chris Mannix (Goggins), entrambi senza più cavalli: inizialmente restii, i due li fanno salire sulla diligenza. Ma la tempesta di neve continua, e il gruppetto si deve rifugiare nel bungalow di Minnie Haberdashery. Solo che, arrivati alla stazione, di Minnie non c&amp;#39;è traccia. Ci sono invece altri quattro stranieri, anche loro in cerca di riparo: il messicano Bob (Bichir), il boia di Red Rock Oswaldo Mobray (Roth), il mandriano Joe Gage (Madsen) e il generale della Confederazione Sanford Smithers (Dern).&#13;
&#13;
Se la prima parte delle tre ore di The Hateful Eight mette subito in chiaro che il film non è esattamente il titolo più disimpegnato da lui diretto, ciò che Tarantino riesce a fare dentro le quattro mura di quel bungalow è a dir poco fenomenale. Poco male che The Hateful Eight non abbia avuto lo stesso riscontro di Django Unchained, anzi: è quasi un fattore naturale, se si analizza la filmografia del regista. Questo è dopotutto il side B di Django Unchained: più teorico, meno ovvio e immediato, più complesso, per nulla mainstream. Ma, come spesso accade coi side B, il risultato è sorprendente.&#13;
&#13;
The Hateful Eight sta a Django Unchained come Death Proof sta a Kill Bill, dove ovviamente i secondi sono i film più acclamati, mentre sui primi si sono riversati tutti i dubbi anche degli aficionados. Questi due sono i film in cui per davvero Tarantino ‘applica’ l’esperienza del cinema di una volta, andando al di là del mare di citazioni e omaggi a cui ci ha abituati. Che, va da sé, ci sono comunque e sono disseminati per tutta la durata: anche se questa volta l&amp;#39;&amp;#34;omaggio&amp;#34; più grande è addirittura quello di una colonna sonora nuova di zecca di Ennio Morricone, semplicemente splendida.&#13;
&#13;
In Death Proof, oltre al look audiovisivo vintage che &amp;#39;imitava&amp;#39; la pellicola che saltava e gracchiava, avevamo il double bill con Planet Terror nel progetto Grindhouse. Con The Hateful Hate, almeno negli States, c&amp;#39;è l&amp;#39;esperienza roadshow del film proiettato in un glorioso 70mm, con tanto di Intermission. Il risultato è, come Death Proof, un film che si appropria di strumenti di altri tempi eppure sembra vivere fuori dal tempo, in un universo che può essere solo dell’autore e di nessun altro. E se Death Proof era il suo film più teorico, questo è il suo più politico.&#13;
&#13;
Così come Jackie Brown è il suo più romantico: ed era all’epoca il side B, considerato assai minore, di Pulp Fiction... Diceva Ebert di Jackie Brown: &amp;#34;Si assapora ogni momento di Jackie Brown. Quelli che dicono che è troppo lungo hanno sviluppato un deficit d&amp;#39;attenzione verso il cinema&amp;#34;. Pensiero che si può benissimo applicare a The Hateful Eight. Che appunto sarà meno &amp;#39;divertente&amp;#39; di Django Unchained, ma ne scansa la ovvietà di narrazione che lo rendevano il meno coraggioso e paradossalmente personale (mica brutto, comunque) dei film del regista.&#13;
&#13;
In Django Unchained, ammetteranno pure i patiti, c&amp;#39;era una trama talmente lineare che portava troppo facilmente il pubblico a tifare per l’eroe. In The Hateful Eight il &amp;#39;problema&amp;#39;, per tutti, starà proprio nel manico: qui di eroi non ce ne sono. E se non ci sono eroi non c&amp;#39;è empatia, non si tifa, e non c&amp;#39;è catarsi. In The Hateful Eight ci sono semmai archetipi che si combattono a vicenda per la supremazia di una nazione divisa in due parti, e dove anche in zona neutra ci si continua a combattere e ferire a suon di insulti e bugie.&#13;
&#13;
Prendiamo quindi quella che per molti è una voragine di sceneggiatura. Senza svelare nulla, diciamo solo che riguarda l&amp;#39;identità di un personaggio, la sua nazionalità, e il modo in cui un altro personaggio lo mette al muro. Tarantino però, qualche scena dopo, sembra essersi dimenticato di questa cosa, facendo indirettamente smentire il &amp;#39;problema&amp;#39; a un altro personaggio ancora. Ma possibile che uno sceneggiatore come Tarantino, così preciso e perfetto e ossessivo nella &amp;#39;pulizia&amp;#39; dello script, si sia lasciato sfuggire un dettaglio mica da poco&amp;#63; Un dubbio però dovrebbe almeno venire.&#13;
&#13;
Qui gli &amp;#39;otto livorosi&amp;#39; non usano solo i cliché delle loro provenienze, del colore della pelle e della loro posizione politica per darsi battaglia, ma usano la menzogna come arma principale. Con la bugia non solo si ferisce e si orchestrano piani, ma addirittura ci si fa riconoscere e rispettare per quello che (non) si è. La menzogna è strumento per costruirsi rispetto e identità di fronte allo straniero. Ed è così che l&amp;#39;odio porta a un inevitabile bagno di sangue: i pregiudizi si alimentano così, e una volta scoperchiate le bugie resta solo da applicare la violenza e la legge della frontiera.&#13;
&#13;
The Hateful Eight è così una vera storia americana, in cui si percepisce chiaramente la natura degli archetipi e la violenza del suo dna. Per questo l&amp;#39;accusa al fatto che non ci sono veri personaggi suona ancora più ridicola: qui innanzitutto si tifa per il Cinema, nello specifico per un cinema in grado di descrivere le fondamenta di una nazione in un modo del genere. Mescolando Agatha Cristie e Sergio Leone, 10 piccoli indiani e Un dollaro d’onore, il mystery d’autore e lo splatter, il teatro sofisticato e il b-movie, il cinema da camera e Carpenter, Hitchcock e le serie tv western anni 60.&#13;
&#13;
E quando Tarantino a metà film interrompe (anche grazie al &amp;#39;solito&amp;#39; uso della divisione in capitoli) la linearità della narrazione, tenendo viva l’atmosfera misteriosa del whodunit, ci esalta ancora per un cinema che non ha nessun paragone in giro. Provate a trovare in giro qualcosa di così claustrofobico eppure intimo, ‘rassicurante’ (perché sai di trovarti in mani esperte) eppure sempre sorprendente. Tutta la seconda metà è davvero magistrale nel ribaltare aspettative e arrivare alle sue conclusioni.&#13;
&#13;
Questo è un film in cui, inspiegabilmente, quando Jennifer Jason Leigh (clamorosa) canta con la chitarra Jim Jones at Botany Bay sale una malinconia incredibile, nonostante la tensione per un fatto narrativo di cui solo il pubblico e il suo personaggio sono consci. Segno che ci sono ragionamenti altri che lavorano sottopelle. Che sia anche un film che richiede una seconda visione è scontato, perché il testo è talmente denso (e si, la prima volta richiede pazienza, questa sconosciuta…) che si rischia di perdere invece il lavoro mostruoso che Tarantino fa per elevarlo mille miglia oltre il ‘teatro filmato’. Cinema cristallino e maturo, che racchiude per davvero tutti i film del regista a partire da Le Iene, e va oltre.&#13;
&#13;
Le accuse di misoginia sono anche peggiori di quelle di chi ancora condanna Tarantino per l’uso della parola nigger (come se Tarantino fosse i suoi personaggi, e come se all’epoca questa parola non fosse ancora più usata di oggi…). Il fatto che tra l&amp;#39;altro in una lettera scritta di suo pugno da Lincoln sia quell’ ‘old Mary Todd&amp;#39;s calling’ a rafforzarne la presunta verità (ovvero il fatto che si citi la presenza della moglie) dovrebbe già far scattare un campanello d’allarme (‘That’s a nice touch’&amp;#33;). Ma è il personaggio di Daisy, che guarda gli uomini trucidarsi e farsi battaglia con sguardo sornione per tutto il film, a fare la differenza, nonostante la violenza a cui è sottoposta.&#13;
&#13;
