=== mzanella/TecWebProject/data/database/DButenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti" targetNamespace="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti" elementFormDefault="qualified">

	<xs:element name="database" type="Tdatabase"/>
	<xs:complexType name="Tdatabase">
		<xs:sequence>
			<xs:element name="utenti" type="Tutenti" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Tutenti">
		<xs:sequence>
			<xs:element name="utente" type="Tutente" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Tutente">
		<xs:sequence>
			<xs:element name="nome" type="xs:string"/>
			<xs:element name="cognome" type="xs:string" />
			<xs:element name="dataDiNascita" type="xs:date" />
			<xs:element name="email" type="xs:string" />
			<xs:element name="password" type="xs:string" />
			<xs:element name="admin" type="Tadmin" />
			<xs:element name="generiPreferiti" type="TgeneriPreferiti" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:decimal" />
	</xs:complexType>

	<xs:simpleType name="Tadmin">
		<xs:restriction base="xs:string">
			<xs:enumeration value="si" />
			<xs:enumeration value="no" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="TgeneriPreferiti">
		<xs:sequence>
			<xs:element name="genere" type="Tgenere" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

<xs:simpleType name="Tgenere">
	<xs:restriction base="xs:string">
		<xs:enumeration value="animazione" />
		<xs:enumeration value="avventura" />
		<xs:enumeration value="azione" />
		<xs:enumeration value="comico" />
		<xs:enumeration value="commedia" />
		<xs:enumeration value="documentario" />
		<xs:enumeration value="dramma" />
		<xs:enumeration value="erotico" />
		<xs:enumeration value="fantascienza" />
		<xs:enumeration value="giallo" />
		<xs:enumeration value="guerra" />
		<xs:enumeration value="horror" />
		<xs:enumeration value="musical" />
		<xs:enumeration value="noir" />
		<xs:enumeration value="sentimentale" />
		<xs:enumeration value="thriller" />
		<xs:enumeration value="western" />
	</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mzanella/TecWebProject/data/database/DButenti.xml
<?xml version="1.0"?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti ../data/database/DButenti.xsd">
<utenti>

<utente id="0">
<nome>Oscar Elia</nome>
<cognome>Conti</cognome>
<dataDiNascita>1992-05-25</dataDiNascita>
<email>oscar@email.com</email>
<password>X03MO1qnZdYdgyfeuILPmQ</password>
<admin>si</admin>
<generiPreferiti><genere>animazione</genere><genere>avventura</genere><genere>erotico</genere></generiPreferiti>
</utente><utente id="1">
<nome>Marco</nome>
<cognome>Zanella</cognome>
<dataDiNascita>1994-07-05</dataDiNascita>
<email>marco@email.com</email>
<password>X03MO1qnZdYdgyfeuILPmQ</password>
<admin>no</admin>
<generiPreferiti><genere>fantascienza</genere><genere>horror</genere></generiPreferiti>
</utente><utente id="2">
<nome>Federico</nome>
<cognome>Tavella</cognome>
<dataDiNascita>1918-01-01</dataDiNascita>
<email>federico@email.com</email>
<password>X03MO1qnZdYdgyfeuILPmQ</password>
<admin>no</admin>
<generiPreferiti><genere>documentario</genere><genere>dramma</genere><genere>musical</genere><genere>sentimentale</genere></generiPreferiti>
</utente></utenti>
</database>
