=== mzanella/TecWebProject/data/database/generi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti" targetNamespace="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti" elementFormDefault="qualified">
	<xs:element name="generi" type="Tgeneri"/>
	<xs:complexType name="Tgeneri">
		<xs:sequence>
			<xs:element name="genere" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== mzanella/TecWebProject/data/database/generi.xml
<?xml version="1.0"?>
<generi xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://tecnologie-web.studenti.math.unipd.it/tecweb/~oconti ../data/database/generi.xsd">
	<genere>animazione</genere>
	<genere>avventura</genere>
	<genere>azione</genere>
	<genere>comico</genere>
	<genere>commedia</genere>
	<genere>documentario</genere>
	<genere>dramma</genere>
	<genere>erotico</genere>
	<genere>fantascienza</genere>
	<genere>giallo</genere>
	<genere>guerra</genere>
	<genere>horror</genere>
	<genere>musical</genere>
	<genere>noir</genere>
	<genere>sentimentale</genere>
	<genere>thriller</genere>
	<genere>western</genere>
</generi>
